package com.example.demo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.PathVariable;
// imports for use List, Map, String and Object

import java.lang.String;

@Controller	// This means that this class is a Controller
@RequestMapping(path="/usuario") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private CursoRepository cursoRepository;



	@PostMapping(path="/add") // Map ONLY POST Requests
	public @ResponseBody String addNewCurso (@RequestParam String name
			, @RequestParam int creditos) {
		Curso n = new Curso();
		n.setNombre(name);
		n.setCreditos(creditos);
		cursoRepository.save(n);
		return "Saved";
	}

	@DeleteMapping(path="/del")
	public @ResponseBody String delCurso (@RequestParam Integer id) {
		Curso n = new Curso();
		n.setId(id);
		cursoRepository.delete(n);
		return "Deleted";
	}

	@PutMapping(path="/edit")
	public @ResponseBody String editUser (@RequestParam Integer id, @RequestParam String name
	, @RequestParam int creditos) {
		Curso n = new Curso();
		n.setId(id);
		n.setNombre(name);
		n.setCreditos(creditos);
		cursoRepository.save(n);
		return "Updated";
	}


	@GetMapping(path="/all")
	public @ResponseBody Iterable<Curso> getAllCurso() {
		return cursoRepository.findAll();
	}

	@GetMapping(path="/get/{id}")
	public @ResponseBody Curso getOneUser(@PathVariable Integer id) {
		return cursoRepository.findById(id).orElse(null);
	}


	


}

